### ISSUE TITLE
Cypress UI tests look at the wrong menu

### ISSUE THREAD

**Issue by skitt** [stolostron/acmqe-mcn-test#271] opened 2023-03-23 13:22 UTC
In my setup, all Cypress tests failed, because they look in the wrong place:

![submariner - Deployment validation -- verify that a cluster set with deployment of submariner is exists (failed)](https://user-images.githubusercontent.com/2128935/227217191-618286f5-ec99-4982-9fe4-aaf7b9b90952.png)

Instead of opening the “local-cluster” menu, the test opened the “Administrator” menu, and failed to find the “All Clusters” entry.

**Comment by MaxBab** [comment] 2023-03-23 13:25
@skitt 

Thank you for the issue.
Which node and npm version are you running with now?
Have you updated the version to a requests in cypress.json file?

**Comment by MaxBab** [comment] 2023-03-23 13:39
The container that executes ci as well as my local env has a version of node:
v18.1.0

I wonder if that could be related.

I'll try a bit later to increase the version and catch the issue.

**Comment by skitt** [comment] 2023-03-23 16:30
Don’t apply the above, the DOM paths need to be made generic.

**Comment by MaxBab** [comment] 2023-03-23 17:55
Before applying the change, I want to be able to reproduce it.
I want to understand the difference between your, mine and ci envs, where it's working.

**Comment by skitt** [comment] 2023-03-24 08:38
I’m not asking you to apply the change, on the contrary, you *mustn’t* apply it; its only purpose is to identify the differences. The failure isn’t related to different versions of `node` or `npm`, it’s caused by changes in the content served by OpenShift and/or the ACM overlay.

**Comment by MaxBab** [comment] 2023-04-02 07:34
@skitt 
I think I found the root cause.
Does your hub had an ocp version 4.13?

**Comment by MaxBab** [comment] 2023-04-02 14:20
Fix by @NogaTal98 
https://github.com/stolostron/acmqe-mcn-test/pull/288

**Comment by skitt** [comment] 2023-04-03 08:46
> @skitt I think I found the root cause. Does your hub had an ocp version 4.13?

Yes, that’s right, see the first screenshot :wink:.

**Comment by MaxBab** [comment] 2023-04-03 08:47
Great.
I'm going to verify it in my setup as well.
And then we will merge it.

**Comment by MaxBab** [comment] 2023-04-04 16:41
Patch with fix has been merged.
https://github.com/stolostron/acmqe-mcn-test/pull/288

**Closed by MaxBab** 2023-04-04 16:41 UTC
